title:
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
description: A minimal blogging theme for Stackbit
header:
  title: Fjord
  tagline: Minimal and clean blog theme
  logo_img: images/logo.png
  background_img: images/header-bg.jpg
  has_nav: true
  nav_links:
    - label: Home
      url: /
      style: link
    - label: Art
      url: /art
      style: link
    - label: Writing
      url: /writing
      style: link
    - label: Science
      url: /science
      style: link
    - label: Memories
      url: /memories
      style: link
    - label: Critique
      url: /critique
      style: link
    - label: Contact
      url: /contact
      style: link
  has_social: true
  social_links:
    - label: Twitter
      url: 'https://twitter.com/sherslifework'
      style: icon
      icon_class: fa-twitter
      new_window: true
    - label: Instagram
      url: 'https://www.instagram.com/sherslifework/'
      style: icon
      icon_class: fa-instagram
      new_window: true
    - label: Facebook
      url: 'https://www.facebook.com/Sherslifework-107327871176700/?view_public_for=107327871176700'
      style: icon
      icon_class: fa-facebook
      new_window: true
footer:
  content: '&copy; All rights reserved.'
  links:
    - label: Made with Stackbit.
      url: 'https://www.stackbit.com'
      style: link
      new_window: true
palette: yellow
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
